version: '3.7'

services:
  db:
    image: postgres:12.2-alpine
    ports:
      - 5436:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test

  api:
    build: .
    command: uvicorn
