name: CI

on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]

    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8.2'

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Test with black
        run: |
          python -m black --check .

      - name: Test with pytest
        env:
          DSN: 'postgresql://test:test@localhost:${{ job.services.postgres.ports[5432] }}/test'
        run: |
          python -m pytest
